spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/tushu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
